package Assignment;

public class Assign2 {
	public static void main(String args[]) {
		
		catch(ArithmeticException e) {
			System.out.println("In catch");
		}
		
	}
}
 
//will show error